### PR TITLE
Real amp ansatz

### PR DESCRIPTION
**Pull request by aljabr0**
Please review my proposed implementation of the Real Amplitudes Ansatz. Alongside I'm also proposing the function `rewire` that remaps a two-qubits gate to arbitrary wires. Note `rewire` is a temporary solution until `#28` will be implemented.
Thanks

### CODE REVIEW

**Comment by toumix** [comment]
Great work thanks! Now that we have more than one, we should probably have a submodule `quantum/ansatze.py`.

My only concern is that evaluating so many circuits (e.g. all the calls to `_assert_is_close`) might slow down the test suite too much. Tests should check that the code does what the maths says, there's no need to check the maths itself.

**Comment by aljabr0** [comment]
Sorry for the obsessive testing, please suggest a guideline so I can review the assertions.
Thanks

**Comment by toumix** [comment]
Testing equality of diagrams is fast, evaluating tensor diagrams is slow.
So the guideline would be something like: keep coverage at 100% with the minimum number of calls to `eval`.
For example, instead of checking `ext_cx(1, 2).eval() == (Id(1) @ CX).eval()`, it is enough to check `ext_cx(1, 2) == (Id(1) @ CX)`.

**Comment by toumix** [comment]
By the way, I've just added a pycodestyle check to the travis CI.
Can you fix the few style errors in your PR and merge the updated main branch?

**Comment by aljabr0** [comment]
All clear, thanks.

**Comment by aljabr0** [comment]
Please review the new tests in which the evals have been reduced.

**Pull request merged**
